reorder_imports = true
group_imports = "StdExternalCrate"
condense_wildcard_suffixes = true
edition = "2021"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true